{{--
    This project has no Tailwind build step of its own (see package.json /
    vite.config.js — only Bootstrap/sass is compiled). All Filament styling
    comes from the package's own pre-built dist/*.css, generated by Filament
    upstream by scanning ONLY its own package sources. Any new Tailwind
    utility class referenced in our published/overridden filament-panels
    views — arbitrary values like `px-[31px]` especially — has no matching
    rule in that stylesheet and silently does nothing. Plain CSS here is the
    reliable way to apply the handful of one-off overrides this project
    needs; the `[class*="…"]` selectors below just latch onto literal
    Alpine-bound class/marker strings already present in the overridden
    blade views (see sidebar/index.blade.php) — they aren't real Tailwind
    classes, just hooks for these rules to target.
--}}
<style>
    .fi-main {
        padding-inline-start: 31px;
        padding-inline-end: 30px;
    }

    /* Table "card grid" mode (->contentGrid() — used by UserResource,
       RoleResource). Filament's own grid component (support/resources/views/
       components/grid/index.blade.php) sets column count through a
       Tailwind arbitrary-value class (`grid-cols-[--cols-default]`) that
       has no compiled rule here (see file header) — the container never
       actually became a grid. Rebuilt directly with `auto-fill`/`minmax()`
       instead of Filament's fixed per-breakpoint column counts, so cards
       pack in by available width — wider desktops simply fit more per row
       rather than being capped at a fixed 3 or 4 columns. 320px is a
       common minimum card width for this kind of compact record card
       (a few text fields + role/permission badges + a handful of action
       icons) — enough room for badges to sit on one line without
       cramping, narrow enough to comfortably fit 4+ per row on a
       standard 1440px desktop. */
    .fi-ta-content-grid {
        display: grid !important;
        grid-template-columns: repeat(auto-fill, minmax(320px, 1fr)) !important;
    }

    @media (min-width: 1024px) {
        .fi-sidebar[class*="lg:w-[--collapsed-sidebar-width]"] {
            width: var(--collapsed-sidebar-width);
        }

        /* Symmetric padding centers the icon button with an even margin on
           both sides. The item's own -mx-2/px-2 wrapping (sidebar/group.blade.php,
           sidebar/item.blade.php) lets the button box extend 0.5rem beyond
           this padding on each side, so with this 1rem nav padding the
           button (1.5rem icon + 0.5rem×2 own padding = 2.5rem) sits with
           an even 0.5rem margin on each side inside the 3.5rem collapsed
           rail (->collapsedSidebarWidth('3.5rem') on every panel provider):
           0.5rem margin + 2.5rem button + 0.5rem margin = 3.5rem. */
        .fi-sidebar-nav[class*="fi-sidebar-nav-collapsed"] {
            padding-inline-start: 1rem;
            padding-inline-end: 1rem;
        }

        /* Category labels are already hidden when collapsed (group.blade.php
           only shows the label row while $store.sidebar.isOpen), leaving
           nothing to mark where one category ends and the next begins — a
           plain horizontal rule stands in for that instead, only while
           collapsed. */
        .fi-sidebar-nav[class*="fi-sidebar-nav-collapsed"] .fi-sidebar-group:not(:first-child) {
            border-top: 1px solid rgba(255, 255, 255, .16);
            padding-top: 1rem;
            margin-top: 0.25rem;
        }

        /* 0.5rem margin each side leaves exactly enough room for the Keluar
           button (1.5rem icon + 0.5rem×2 own padding = 2.5rem) inside the
           3.5rem collapsed rail, with no slack to spare — see
           sidebar-footer.blade.php. */
        .fi-sidebar-footer[class*="fi-sidebar-footer-collapsed"] {
            padding-inline-start: 0.5rem;
            padding-inline-end: 0.5rem;
        }

        /* A regular nav item's button (sidebar/item.blade.php) is a block
           that stretches to the full width of its <li> — fine when the
           label is visible next to it, but once the label is hidden while
           collapsed it leaves a full-width hover/active box instead of a
           small icon chip, unlike the Keluar button in the footer (which
           is sized to its own content). Shrinking it to fit and centering
           it matches that same compact sizing. */
        .fi-sidebar-nav[class*="fi-sidebar-nav-collapsed"] .fi-sidebar-item-button {
            width: fit-content;
            margin-inline: auto;
        }
    }

    /* ==========================================================
       Sidebar & topbar chrome, aligned with the login screen's dark
       gradient + glass look (resources/views/auth/login.blade.php).
       Scoped to the persistent navigation only — the main content
       area (tables, forms) stays light for readability. Dark mode is
       disabled panel-wide (`->darkMode(false)`), so Filament's own
       `dark:` variants never engage; these are plain overrides of the
       light-theme classes it renders instead.
       ========================================================== */
    .fi-sidebar,
    .fi-topbar nav {
        background: linear-gradient(135deg, #0f172a 0%, #1e3a8a 45%, #4f46e5 100%);
    }

    .fi-sidebar {
        border-inline-end: 1px solid rgba(255, 255, 255, .16);
    }

    .fi-topbar nav {
        border-bottom: 1px solid rgba(255, 255, 255, .16);
        box-shadow: none;
    }

    .fi-sidebar-header {
        background: transparent !important;
        box-shadow: none !important;
        border-color: rgba(255, 255, 255, .16) !important;
    }

    .fi-logo,
    .fi-logo * {
        color: #fff !important;
    }

    .fi-sidebar-identity-trigger:hover {
        background-color: rgba(255, 255, 255, .1) !important;
    }

    .fi-sidebar-identity-role {
        color: rgba(255, 255, 255, .6) !important;
    }

    .fi-sidebar-group-label,
    .fi-sidebar-group-icon,
    .fi-sidebar-group-collapse-button {
        color: rgba(255, 255, 255, .55) !important;
    }

    .fi-sidebar-item-button {
        color: #fff !important;
    }

    .fi-sidebar-item-button:hover {
        background-color: rgba(255, 255, 255, .08) !important;
    }

    .fi-sidebar-item-icon {
        color: #fff !important;
    }

    {{-- The label <span> carries its own text-gray-700 class (see
         sidebar/item.blade.php), so it doesn't just inherit color from the
         parent button above — it needs its own explicit override too. --}}
    .fi-sidebar-item-label {
        color: #fff !important;
    }

    .fi-sidebar-item.fi-active .fi-sidebar-item-button {
        background-color: rgba(255, 255, 255, .14) !important;
    }

    .fi-sidebar-item.fi-active .fi-sidebar-item-icon,
    .fi-sidebar-item.fi-active .fi-sidebar-item-label {
        color: #93c5fd !important;
    }

    .fi-sidebar-footer {
        border-color: rgba(255, 255, 255, .16) !important;
    }

    /* "Keluar" trigger (dropdown or plain button — sidebar-footer.blade.php
       picks whichever applies) is a solid filled danger button, not just
       red text — reuses Filament's own danger-600/700 red tones. */
    .fi-sidebar-footer .fi-sidebar-item-button {
        color: #fff !important;
        background-color: #dc2626 !important;
    }

    .fi-sidebar-footer .fi-sidebar-item-button:hover {
        background-color: #b91c1c !important;
    }

    .fi-sidebar-footer .fi-sidebar-item-icon {
        color: #fff !important;
    }

    .fi-topbar .fi-icon-btn {
        color: rgba(255, 255, 255, .7) !important;
    }

    .fi-topbar .fi-icon-btn:hover {
        color: #fff !important;
        background-color: rgba(255, 255, 255, .08) !important;
    }

    /* ==========================================================
       Page footer. Truly fixed to the viewport bottom, same dark
       gradient as the sidebar/topbar so the three read as one
       continuous shell around the light content area.

       Fixed positioning escapes .fi-main-ctn entirely, so its `left`
       offset has to track the sidebar's width by hand instead of
       inheriting it from layout the way sticky would have. `.fi-main-ctn-
       sidebar-open` is Filament's own marker (already toggled live by
       Alpine in layout/index.blade.php) for whether the sidebar is
       currently expanded or the narrow 3.5rem rail — reused here rather
       than tracking that state a second time. --sidebar-width /
       --collapsed-sidebar-width are Filament's own CSS variables (set
       in layout/base.blade.php from ->collapsedSidebarWidth()). Below
       the lg breakpoint the sidebar is an off-canvas drawer overlay
       rather than something the content flows beside, so the footer
       just spans full width there.

       Height is a fixed 64px to match .fi-sidebar-footer's own rendered
       height (sidebar-footer.blade.php) so the two footers line up.
       Fixed height means content that would wrap to a second line just
       gets clipped (see the credit line's mobile hide below) instead of
       growing the footer — deliberate trade-off for a guaranteed match.

       .fi-main is height-capped to the viewport (below) and scrolls
       internally, with its own bottom padding reserving these same
       64px so content never sits behind the footer. That capping is
       also what keeps .fi-layout from ever exceeding 100vh — letting it
       grow taller (which the old padding-bottom-on-flow-content
       approach did) is what caused .fi-sidebar to visually "lift": the
       sidebar is `position: sticky` with both `top: 0` and `bottom: 0`
       set (inset-y-0, sidebar/index.blade.php) so it stays pinned
       full-height, but a sticky element with both offsets releases its
       top-pin and starts tracking the bottom offset instead once its
       containing block's far edge comes into view — exactly what
       scrolling to the bottom of a taller-than-100vh page triggered. */
    .fi-page-footer {
        position: fixed;
        right: 0;
        bottom: 0;
        left: 0;
        z-index: 20;
        height: 64px;
        overflow: hidden;
        display: flex;
        flex-direction: column;
        background: linear-gradient(135deg, #0f172a 0%, #1e3a8a 45%, #4f46e5 100%);
    }

    @media (min-width: 1024px) {
        .fi-main-ctn:not(.fi-main-ctn-sidebar-open) .fi-page-footer {
            left: var(--collapsed-sidebar-width);
        }

        .fi-main-ctn.fi-main-ctn-sidebar-open .fi-page-footer {
            left: var(--sidebar-width);
        }
    }

    /* .fi-main-ctn's children (topbar h-16 = 64px, then .fi-main below)
       are left to sum to exactly 100vh instead of letting .fi-main grow
       past its share — see the big comment above .fi-page-footer for
       why that matters for the sidebar. */
    .fi-main {
        height: calc(100vh - 64px);
        overflow-y: auto;
        padding-bottom: 64px;
    }

    /* The one deliberate flourish: a slim gradient seam stitching the
       footer to the same brand gradient used everywhere else, instead of
       a flat border-top. */
    .fi-page-footer-hairline {
        height: 2px;
        flex-shrink: 0;
        background: linear-gradient(90deg, #0f172a, #1e3a8a, #4f46e5, #a855f7);
    }

    /* Fills the remaining 62px below the hairline (footer's fixed 64px
       total) and vertically centers a single text line — no vertical
       padding needed since height:100% + align-items already center it.
       overflow: hidden clips rather than wraps if flex-wrap ever kicks
       in, keeping the 64px height exact (see .fi-page-footer-credit
       below for the deliberate narrow-screen fallback instead). */
    .fi-page-footer-inner {
        flex: 1;
        min-height: 0;
        display: flex;
        flex-wrap: wrap;
        align-items: center;
        justify-content: space-between;
        gap: 0.375rem 1.5rem;
        padding: 0 31px;
        font-size: 0.75rem;
        line-height: 1.25rem;
        overflow: hidden;
    }

    @media (max-width: 640px) {
        .fi-page-footer-credit {
            display: none;
        }
    }

    .fi-page-footer-brand {
        display: flex;
        align-items: center;
        gap: 0.5rem;
        color: rgba(255, 255, 255, .65);
        white-space: nowrap;
    }

    /* Echoes the pulsing status dot on the login screen's brand badge
       (resources/views/auth/login.blade.php, .badge-dot) — same green,
       same rhythm — so the footer reads as a continuation of that
       language rather than a new one. */
    .fi-page-footer-dot {
        width: 6px;
        height: 6px;
        border-radius: 9999px;
        background: #4ade80;
        flex-shrink: 0;
        animation: fi-page-footer-blink 2.2s ease-in-out infinite;
    }

    @keyframes fi-page-footer-blink {
        0%, 100% {
            opacity: 1;
        }

        50% {
            opacity: .35;
        }
    }

    .fi-page-footer-brand-name {
        font-weight: 700;
        color: #fff;
    }

    .fi-page-footer-divider {
        color: rgba(255, 255, 255, .3);
    }

    .fi-page-footer-credit {
        display: flex;
        align-items: center;
        gap: 0.375rem;
        color: rgba(255, 255, 255, .55);
    }

    .fi-page-footer-credit-icon {
        width: 1rem;
        height: 1rem;
        flex-shrink: 0;
        color: rgba(255, 255, 255, .4);
    }
</style>
