{{--
    This project has no Tailwind build step of its own (see package.json /
    vite.config.js — only Bootstrap/sass is compiled). All Filament styling
    comes from the package's own pre-built dist/*.css, generated by Filament
    upstream by scanning ONLY its own package sources. Any new Tailwind
    utility class referenced in our published/overridden filament-panels
    views — arbitrary values like `px-[31px]` especially — has no matching
    rule in that stylesheet and silently does nothing. Plain CSS here is the
    reliable way to apply the handful of one-off overrides this project
    needs; the `[class*="…"]` selectors below just latch onto literal
    Alpine-bound class/marker strings already present in the overridden
    blade views (see sidebar/index.blade.php) — they aren't real Tailwind
    classes, just hooks for these rules to target.
--}}
<style>
    .fi-main {
        padding-inline-start: 31px;
        padding-inline-end: 30px;
    }

    @media (min-width: 1024px) {
        .fi-sidebar[class*="lg:w-[--collapsed-sidebar-width]"] {
            width: var(--collapsed-sidebar-width);
        }

        /* Symmetric padding centers the icon button with an even margin on
           both sides. The item's own -mx-2/px-2 wrapping (sidebar/group.blade.php,
           sidebar/item.blade.php) lets the button box extend 0.5rem beyond
           this padding on each side, so with this 1rem nav padding the
           button (1.5rem icon + 0.5rem×2 own padding = 2.5rem) sits with
           an even 0.5rem margin on each side inside the 3.5rem collapsed
           rail (->collapsedSidebarWidth('3.5rem') on every panel provider):
           0.5rem margin + 2.5rem button + 0.5rem margin = 3.5rem. */
        .fi-sidebar-nav[class*="fi-sidebar-nav-collapsed"] {
            padding-inline-start: 1rem;
            padding-inline-end: 1rem;
        }

        /* Category labels are already hidden when collapsed (group.blade.php
           only shows the label row while $store.sidebar.isOpen), leaving
           nothing to mark where one category ends and the next begins — a
           plain horizontal rule stands in for that instead, only while
           collapsed. */
        .fi-sidebar-nav[class*="fi-sidebar-nav-collapsed"] .fi-sidebar-group:not(:first-child) {
            border-top: 1px solid rgba(255, 255, 255, .16);
            padding-top: 1rem;
            margin-top: 0.25rem;
        }

        /* 0.5rem margin each side leaves exactly enough room for the Keluar
           button (1.5rem icon + 0.5rem×2 own padding = 2.5rem) inside the
           3.5rem collapsed rail, with no slack to spare — see
           sidebar-footer.blade.php. */
        .fi-sidebar-footer[class*="fi-sidebar-footer-collapsed"] {
            padding-inline-start: 0.5rem;
            padding-inline-end: 0.5rem;
        }

        /* A regular nav item's button (sidebar/item.blade.php) is a block
           that stretches to the full width of its <li> — fine when the
           label is visible next to it, but once the label is hidden while
           collapsed it leaves a full-width hover/active box instead of a
           small icon chip, unlike the Keluar button in the footer (which
           is sized to its own content). Shrinking it to fit and centering
           it matches that same compact sizing. */
        .fi-sidebar-nav[class*="fi-sidebar-nav-collapsed"] .fi-sidebar-item-button {
            width: fit-content;
            margin-inline: auto;
        }
    }

    /* ==========================================================
       Sidebar & topbar chrome, aligned with the login screen's dark
       gradient + glass look (resources/views/auth/login.blade.php).
       Scoped to the persistent navigation only — the main content
       area (tables, forms) stays light for readability. Dark mode is
       disabled panel-wide (`->darkMode(false)`), so Filament's own
       `dark:` variants never engage; these are plain overrides of the
       light-theme classes it renders instead.
       ========================================================== */
    .fi-sidebar,
    .fi-topbar nav {
        background: linear-gradient(135deg, #0f172a 0%, #1e3a8a 45%, #4f46e5 100%);
    }

    .fi-sidebar {
        border-inline-end: 1px solid rgba(255, 255, 255, .16);
    }

    .fi-topbar nav {
        border-bottom: 1px solid rgba(255, 255, 255, .16);
        box-shadow: none;
    }

    .fi-sidebar-header {
        background: transparent !important;
        box-shadow: none !important;
        border-color: rgba(255, 255, 255, .16) !important;
    }

    .fi-logo,
    .fi-logo * {
        color: #fff !important;
    }

    .fi-sidebar-identity-trigger:hover {
        background-color: rgba(255, 255, 255, .1) !important;
    }

    .fi-sidebar-identity-role {
        color: rgba(255, 255, 255, .6) !important;
    }

    .fi-sidebar-group-label,
    .fi-sidebar-group-icon,
    .fi-sidebar-group-collapse-button {
        color: rgba(255, 255, 255, .55) !important;
    }

    .fi-sidebar-item-button {
        color: #fff !important;
    }

    .fi-sidebar-item-button:hover {
        background-color: rgba(255, 255, 255, .08) !important;
    }

    .fi-sidebar-item-icon {
        color: #fff !important;
    }

    {{-- The label <span> carries its own text-gray-700 class (see
         sidebar/item.blade.php), so it doesn't just inherit color from the
         parent button above — it needs its own explicit override too. --}}
    .fi-sidebar-item-label {
        color: #fff !important;
    }

    .fi-sidebar-item.fi-active .fi-sidebar-item-button {
        background-color: rgba(255, 255, 255, .14) !important;
    }

    .fi-sidebar-item.fi-active .fi-sidebar-item-icon,
    .fi-sidebar-item.fi-active .fi-sidebar-item-label {
        color: #93c5fd !important;
    }

    .fi-sidebar-footer {
        border-color: rgba(255, 255, 255, .16) !important;
    }

    /* "Keluar" trigger (dropdown or plain button — sidebar-footer.blade.php
       picks whichever applies) is a solid filled danger button, not just
       red text — reuses Filament's own danger-600/700 red tones. */
    .fi-sidebar-footer .fi-sidebar-item-button {
        color: #fff !important;
        background-color: #dc2626 !important;
    }

    .fi-sidebar-footer .fi-sidebar-item-button:hover {
        background-color: #b91c1c !important;
    }

    .fi-sidebar-footer .fi-sidebar-item-icon {
        color: #fff !important;
    }

    .fi-topbar .fi-icon-btn {
        color: rgba(255, 255, 255, .7) !important;
    }

    .fi-topbar .fi-icon-btn:hover {
        color: #fff !important;
        background-color: rgba(255, 255, 255, .08) !important;
    }
</style>
